name: test go
on: push
jobs:
  myjob:
    name: golang version
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
      - run: go version
